version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      VITE_JWT_SECRET: "MyVerySecretJwtKeyThatIWantNoOneToKnowThatExists"
      VITE_POSTGRES_URL: "postgresql://postgres:password@postgres"
      ORIGIN: "http://localhost:3000"

  postgres:
    image: "docker.io/postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "password"
