version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - ORIGIN=http://localhost:3000

  postgres:
    image: "docker.io/postgres:alpine"
    hostname: "postgres"
    environment:
      POSTGRES_PASSWORD: "password"
